# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimation of the state-space model system matrices with the EM procedure
#' from Shumway and Stoffer (1982)
#'
#' \code{shumway_EM} and \code{shumway_EM_list} compute the estimates of the system matrices T, Q, H for time series modeled according to the following state-space model:
#' \deqn{\boldsymbol{\alpha}_t  = \mathbf{T} \boldsymbol{\alpha}_{t-1} + \boldsymbol{\xi}_t\,, \quad \boldsymbol{\xi}_t \sim \mathcal{N}\left(0,\  \mathbf{Q}\right),}
#' \deqn{\mathbf{z}_t  = \boldsymbol{\alpha}_t + \boldsymbol{\zeta}_t\,, \qquad \boldsymbol{\zeta}_t\sim \mathcal{N}\left(0,\ \mathbf{H}\right).} 
#' IMPORTANT: T, Q and H are assumed to be diagonal.
#' 
#' @name ShSt_EM
NULL

#' @describeIn ShSt_EM Computes the estimate for a single time series.
#' @param z A matrix representing time series. Each row represents a time
#' observation.
#' @param a0 Initial state (expectation).
#' @param P0 Diagonal of the variance matrix of the initial state. 
#' @param TT The diagonal of the matrix of state transformation.
#' @param Q  The diagonal of the variance matrix of the state error.
#' @param H  The diagonal of the variance matrix of the observation error.
#' @param EM_toll Tolerance for the relative difference of log-likelihoods criterion to stop the computation.
#' @param EM_maxit Maximum number of EM iterations.
#' @param verbose A non-negative integer to indicate if and how frequently print 
#' the current system matrices and likelihood as the EM iterations proceed.
#' 
#' @return \code{shumway_EM} returns a list containing:
#' \describe{
#' \item{TT}{Estimated matrix of state transformation.}
#' \item{Q}{Estimated variance matrix of the state error.}
#' \item{H}{Estimated variance matrix of the observation error.}
#' \item{a0}{Estimated initial state.}
#' \item{P0}{Estimated variance of the obtained initial state.}
#' \item{code}{A value indicating the exit condition of the algorithm. 0 means
#' convergence, 1 means that the maximum of iterations has been reached,
#' 2 means a decrease (instead of increase) of the log-likelihood, and 3 means
#' a \code{nan} likelihood.}
#' \item{EM_it}{Number of performed EM iterations.}
#' \item{log_lik}{Final marginal log-likelihood.}
#' \item{diff}{Relative log-likelihood difference at the last iteration.}
#' } 
#' @export
shumway_EM <- function(z, a0, P0, TT, Q, H, EM_toll = 1e-4, EM_maxit = 1e2L, verbose = 0L) {
    .Call(`_compStateSpace_shumway_EM`, z, a0, P0, TT, Q, H, EM_toll, EM_maxit, verbose)
}

#' @describeIn ShSt_EM computes the estimates for a list of series assumed to 
#' share the same system matrices. A weight vector \code{probs} can be provided 
#' if the series do not contribute in the same way to the total likelihood,
#' for example in a mixture model.
#' @param z_list A list of time series. Each element of the list should be a
#' matrix where each row represents a time observation.
#' @param a0_l List of initial states (expectations). Check the `Details`
#' @param P0_l List of variances of the initial states. Check the `Details`
#' @param TT Matrix of state transformation. It should be diagonal.
#' @param Q Variance matrix of the state error. It should be diagonal.
#' @param H Variance matrix of the observation error. It should be diagonal.
#' @param probs Weight vector, containing a value in [0,1] for each of the time series. Check the `Details`.
#' @param EM_toll Tolerance for the relative difference of log-likelihoods criterion to stop the computation.
#' @param EM_maxit Maximum number of EM iterations.
#' @param verbose A non-negative integer to indicate if and how frequently print 
#' the current system matrices and likelihood as the EM iterations proceed.
#' @details
#' For compositional time series, the ilr transformation of the series should be provided. If \code{y_list} is a list of matrices representing compositional times series, with D (= number of parts) columns each, and rows depending on the length of the series, then \code{z_list <- lapply(y_list, \link{comp_to_ilr})}, should be enough.
#' 
#' \code{a0_l} and \code{P0_l} should be a list of length equal to the number of series N. Each element should contain a vector with the same size of a single time-stamp observation: the starting point for \code{a0_l} and the diagonal of the corresponding variance matrix for \code{P0_l}.
#' 
#' In the mixture case, \code{probs} should contain a value between 0 and 1 for each of the time series, corresponding to the probability of the series to belong to the currently considered component. This happens, for example, when \link{mb_clust} is called. If, instead, there are no mixtures involved and the series are all supposed to behave according to the same system matrices, \code{probs} should be a N-dimensional vector of ones.
#'  
#' @return \code{shumway_EM_list} returns a list containing:
#' \describe{
#' \item{TT}{Estimated matrix of state transformation.}
#' \item{Q}{Estimated variance matrix of the state error.}
#' \item{H}{Estimated variance matrix of the observation error.}
#' \item{a0_list}{Estimated initial state.}
#' \item{P0_list}{Estimated variance of the obtained initial state.}
#' \item{code}{A value indicating the exit condition of the algorithm. 0 means convergence, 1 means that the maximum of iterations has been reached, 2 means a decrease (instead of increase) of the log-likelihood, and 3 means a \code{nan} likelihood.}
#' \item{EM_it}{Number of performed EM iterations.}
#' \item{na_lik_series}{Index of the series that gives the \code{nan} likelihood, if \code{code} = 3. -1 otherwise}
#' \item{log_lik}{Final weighted marginal log-likelihood.}
#' \item{diff}{Relative log-likelihood difference at the last iteration.}
#' } 
#' @references
#' Shumway, R. H. and Stoffer, D. S. (1982) An approach to time series smoothing and forecasting using the EM algorithm. Journal of Time Series Analysis 3(4), 253–264.
#' 
#' Shumway, R. H. and Stoffer, D. S. (2000) Time Series Analysis and its Applications. Volume 3. Springer
#' @export
shumway_EM_list <- function(z_list, a0_l, P0_l, TT, Q, H, probs, EM_toll = 1e-4, EM_maxit = 1e2L, verbose = 0L) {
    .Call(`_compStateSpace_shumway_EM_list`, z_list, a0_l, P0_l, TT, Q, H, probs, EM_toll, EM_maxit, verbose)
}

#' Kalman filtering and smoothing of time series
#'
#' \code{k_filter} and \code{k_smoother} compute the filtered and smoothed estimates of time series modeled according to the following state-space model:
#' \deqn{\boldsymbol{\alpha}_t  = \mathbf{T} \boldsymbol{\alpha}_{t-1} + \boldsymbol{\xi}_t\;,\quad \boldsymbol{\xi}_t \sim \mathcal{N}\left(0,\  \mathbf{Q}\right),}
#' \deqn{\mathbf{z}_t  = \boldsymbol{\alpha}_t + \boldsymbol{\zeta}_t\,,\qquad \boldsymbol{\zeta}_t\sim \mathcal{N}\left(0,\ \mathbf{H}\right).} 
#' IMPORTANT: T, Q and H are assumed to be diagonal.
#' @name ShSt_KFS
NULL

#' @describeIn ShSt_KFS Computes the filtered estimates for a time series.
#' @param z A matrix representing time series. Each row represents a time
#' observation.
#' @param a0 Initial state (expectation).
#' @param P0 Diagonal of the variance matrix of the initial state. 
#' @param TT The diagonal of the matrix of state transformation.
#' @param Q  The diagonal of the variance matrix of the state error.
#' @param H  The diagonal of the variance matrix of the observation error.
#' @details The predicted estimates and their variances are defined as
#' \deqn{\mathbf{a}_{t}^{t-1} = \mathbb{E}\left(\boldsymbol{\alpha}_{t} \mid \mathbf{Z}_{1:{t-1}}\right),\quad \mathbf{P}_{t}^{t-1} = \mathbb{V}\text{ar}\left(\boldsymbol{\alpha}_{t} \mid \mathbf{Z}_{1:{t-1}}\right),}
#' where \eqn{\mathbf{Z}_{1:{t-1}}} denotes the series observed up to time \eqn{t-1}. 
#' The filtered estimates and their variances are defined as
#' \deqn{\mathbf{a}_{t}^{t} = \mathbb{E}\left(\boldsymbol{\alpha}_{t} \mid \mathbf{Z}_{1:{t}}\right),\quad \mathbf{P}_{t}^{t} = \mathbb{V}\text{ar}\left(\boldsymbol{\alpha}_{t} \mid \mathbf{Z}_{1:{t}}\right).}
#' @return A list containing:
#' \describe{
#' \item{alpha_next}{Matrix of predicted estimates \eqn{\mathbf{a}_t^{t-1}}.}
#' \item{alpha_current}{Matrix of filtered estimates \eqn{\mathbf{a}_t^t}.}
#' \item{P_next}{Estimated variances of the predicted estimates.}
#' \item{P_current}{Estimated variances of the filtered estimates.}
#' \item{log_lik}{Marginal log-likelihood.}
#' \item{K_n}{Final Kalman gain - useful for smoothing.}
#' } 
#' @export
k_filter <- function(z, a0, P0, TT, Q, H) {
    .Call(`_compStateSpace_k_filter`, z, a0, P0, TT, Q, H)
}

#' @describeIn ShSt_KFS Computes the smoothed estimates for a time series, given
#' the filtered estimates.
#' @param filtered A list of results from `k_filter`.
#' @param TT Matrix of state transformation.
#' @details The smoothed estimates and their variances are defined as
#' \deqn{\mathbf{a}_{t}^{n} = \mathbb{E}\left(\boldsymbol{\alpha}_{t} \mid \mathbf{Z}\right),\quad \mathbf{P}_{t}^{n} = \mathbb{V}\text{ar}\left(\boldsymbol{\alpha}_{t} \mid \mathbf{Z}\right),}
#' that is, having knowledge of the whole observed series.
#' @return \code{k_smoother} returns a list containing:
#' \describe{
#' \item{alpha}{Matrix of smoothed estimates \eqn{\mathbf{a}_t^{n}}.}
#' \item{V}{Estimated variances of the smoothed estimates.}
#' \item{P_lag}{Lag-One covariance smoother - useful to estimate the system matrices.}
#' } 
#' @references 
#' Shumway, R. H. and Stoffer, D. S. (2000) Time Series Analysis and its Applications. 
#' Volume 3. Springer
#' @export
k_smoother <- function(filtered, TT) {
    .Call(`_compStateSpace_k_smoother`, filtered, TT)
}

#' Model-based clustering of time series based on a state space representation
#'
#' \code{mb_clust} performes the model-based clustering of time series, relying on a state-space representation and a mixture of experts model for the inclusion of series-specific covariates. The method was initially developed for clustering compositional time series according to their evolution in the simplex, by feeding the function their ilr-transformed version. 
#'
#' @param z_list A list of time series. Each element of the list should be a matrix where each row represents a time observation.
#' @param a0_l List of initial states (expectations).
#' @param P0_l List of variances of the initial states.
#' @param g_T List of initial group-specific matrices of state transformation. The matrices should be diagonal.
#' @param g_Q List of initial group-specific variance matrices of the state error. The matrices should be diagonal.
#' @param g_H List of initial group-specific variance matrices of the observation error. The matrices should be diagonal.
#' @param x_list List of series-specific covariates.
#' @param g_gamma List of initial values for the component weights parameters.
#' @param clust_maxit Maximum number of EM iterations.
#' @param clust_toll Tolerance for the relative difference of log-likelihoods criterion to stop the computation.
#' @param verbose A non-negative integer to indicate if and how frequently print the likelihood as the EM iterations proceed.
#' @details
#' For compositional time series, the ilr transformation of the series should be provided. \code{z_list <- lapply(y_list, comp_to_ilr)}, where \code{y_list} is a list of matrices with D (= number of parts) columns each, and rows depending on the length of the series, should be enough.
#' 
#' \code{g_T}, \code{g_Q} and \code{g_H} should be lists of length K, where K is the number of groups. Either these, or the values in \code{g_gamma}`, should all be different to ensure the avoidance of identical groups. We recommend providing different starting values for \code{g_T}, \code{g_Q} and \code{g_H}, rather than \code{g_gamma}. A suggested initialization involves the use of a quick clustering procedure (e.g. using \link[dtwclust]{tsclust} from the \code{dtwclust} package) and then some iterations of \link{shumway_EM_list} applied separately to the obtained clusters.
#' 
#' \code{a0_l} and \code{P0_l} should be one of the following: a list (of length K) of lists (each of length equal to the number of series N), or a list of length N. In the former case, the initial states are assumed to be provided for each series for each component. It is useful, for instance, to continue the computation after having obtained a result from the model, if some more iterations are needed. In the latter case, a starting point is assumed to be given for each series, and it is used for the computation for each component. For example, if the initialization with \link{shumway_EM_list} is employed, the obtained results for each series could be used.
#' 
#' \code{x_list} should be of length N, with each covariate vector being series-specific rather than "time-stamp-specific". Every element of the list should be a (P+1)-dimensional vector with 1 as first element, for the intercept.
#' 
#' \code{g_gamma} should be a list of length K, with each element a (P+1)-dimensional vector. The first element is never updated for identifiability reasons, so it should act as reference and a vector of zeros is suggested for it. If the elements in \code{g_T}, \code{g_Q}, and \code{g_H} have been differentiated with an initialization procedure, and no previous knowledge is involved, we suggest to use vectors of zeros for all the component weights parameters, in a sort of "non-informative prior" fashion.
#' 
#' If \code{verbose} is 0, nothing is printed during the computation. If it is a positive integer, the current likelihood and likelihood difference from the previous iteration is printed every \code{verbose} iterations.
#' 
#' 
#' @return A list containing:
#' \describe{
#' \item{groups_T}{A list with the final group-specific matrices of state transformation.}
#' \item{groups_Q}{A list with the final group-specific variance matrices of the state error.}
#' \item{groups_H}{A list with the final group-specific variance matrices of the observation error.}
#' \item{groups_a0_list}{A list of length K of lists, each of which shows the obtained initial states of each series for the corresponding component.}
#' \item{groups_P0_list}{A list of length K of lists, each of which shows the variance of the obtained initial states of each series for the corresponding component.}
#' \item{code}{A value indicating convergence (0) or not (1) of the algorithm.}
#' \item{clust_it}{Number of performed EM iterations.}
#' \item{total_lik}{Final complete log-likelihood.}
#' \item{clust_lik_diff}{Relative log-likelihood difference at the last iteration.}
#' \item{groups_probs_list}{A list with the probability of each series to belong to each component.}
#' \item{gamma}{A list with the final component weight parameters.}
#' \item{time}{Total computational time.}
#' }
#' @export
mb_clust <- function(z_list, a0_l, P0_l, g_T, g_Q, g_H, x_list, g_gamma, clust_maxit = 1e3L, clust_toll = 1e-6, verbose = 0L) {
    .Call(`_compStateSpace_mb_clust`, z_list, a0_l, P0_l, g_T, g_Q, g_H, x_list, g_gamma, clust_maxit, clust_toll, verbose)
}

